#!/usr/bin/env python3

import os
import shutil
import ipsw
import platform

if __name__ =="__main__":
    if platform.system() != 'Darwin':
        print("Sorry this OS is not supported!\nOnly MacOS machines (Hackintosh or a legitimate Apple computer) are support as of now.")
        exit(20)
    if os.path.exists("resources/restoreFiles/igetnonce"):
        shutil.move("resources/restoreFiles/igetnonce", "igetnonce")
    if os.path.exists("resources/restoreFiles/tsschecker"):
        shutil.move("resources/restoreFiles/tsschecker", "tsschecker")
    if os.path.exists("resources/restoreFiles/futurerestore"):
        shutil.move("resources/restoreFiles/futurerestore", "futurerestore")
    if os.path.exists("resources/restoreFiles/irecovery"):
        shutil.move("resources/restoreFiles/irecovery", "irecovery")
    print('\033[95m' + "Vieux - A tool for 32/64 Bit OTA downgrades" + '\033[0m')
    print("Still in " + '\033[91m' + "BETA" + '\033[0m' + " so expect issues/broken things")
    print("If you are using a 64 Bit device then connect it in DFU Mode\nIf you are using a 32 Bit device then just have it connected in normal mode")
    ipsw.unzipIPSW()
    done = False
    print("Cleaning up files...")
    ipsw.removeFiles(done)
    if os.path.exists("igetnonce"):
        shutil.move("igetnonce", "resources/restoreFiles/igetnonce")
    if os.path.exists("tsschecker"):
        shutil.move("tsschecker", "resources/restoreFiles/tsschecker")
    if os.path.exists("futurerestore"):
        shutil.move("futurerestore", "resources/restoreFiles/futurerestore")
    if os.path.exists("irecovery"):
        shutil.move("irecovery", "resources/restoreFiles/irecovery")
    print('\033[92m' + ''"Finished! Enjoy your downgraded phone :)" + '\033[0m')
    exit(0)

